// Generated by gencpp from file learning_communication/Addnums.msg
// DO NOT EDIT!


#ifndef LEARNING_COMMUNICATION_MESSAGE_ADDNUMS_H
#define LEARNING_COMMUNICATION_MESSAGE_ADDNUMS_H

#include <ros/service_traits.h>


#include <learning_communication/AddnumsRequest.h>
#include <learning_communication/AddnumsResponse.h>


namespace learning_communication
{

struct Addnums
{

typedef AddnumsRequest Request;
typedef AddnumsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Addnums
} // namespace learning_communication


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::learning_communication::Addnums > {
  static const char* value()
  {
    return "f1cb8f566c11d405aa88b8f8cec18e85";
  }

  static const char* value(const ::learning_communication::Addnums&) { return value(); }
};

template<>
struct DataType< ::learning_communication::Addnums > {
  static const char* value()
  {
    return "learning_communication/Addnums";
  }

  static const char* value(const ::learning_communication::Addnums&) { return value(); }
};


// service_traits::MD5Sum< ::learning_communication::AddnumsRequest> should match
// service_traits::MD5Sum< ::learning_communication::Addnums >
template<>
struct MD5Sum< ::learning_communication::AddnumsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::learning_communication::Addnums >::value();
  }
  static const char* value(const ::learning_communication::AddnumsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::learning_communication::AddnumsRequest> should match
// service_traits::DataType< ::learning_communication::Addnums >
template<>
struct DataType< ::learning_communication::AddnumsRequest>
{
  static const char* value()
  {
    return DataType< ::learning_communication::Addnums >::value();
  }
  static const char* value(const ::learning_communication::AddnumsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::learning_communication::AddnumsResponse> should match
// service_traits::MD5Sum< ::learning_communication::Addnums >
template<>
struct MD5Sum< ::learning_communication::AddnumsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::learning_communication::Addnums >::value();
  }
  static const char* value(const ::learning_communication::AddnumsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::learning_communication::AddnumsResponse> should match
// service_traits::DataType< ::learning_communication::Addnums >
template<>
struct DataType< ::learning_communication::AddnumsResponse>
{
  static const char* value()
  {
    return DataType< ::learning_communication::Addnums >::value();
  }
  static const char* value(const ::learning_communication::AddnumsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // LEARNING_COMMUNICATION_MESSAGE_ADDNUMS_H
