// Generated by gencpp from file learning_communication/AddnumsResponse.msg
// DO NOT EDIT!


#ifndef LEARNING_COMMUNICATION_MESSAGE_ADDNUMSRESPONSE_H
#define LEARNING_COMMUNICATION_MESSAGE_ADDNUMSRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace learning_communication
{
template <class ContainerAllocator>
struct AddnumsResponse_
{
  typedef AddnumsResponse_<ContainerAllocator> Type;

  AddnumsResponse_()
    : c(0)  {
    }
  AddnumsResponse_(const ContainerAllocator& _alloc)
    : c(0)  {
  (void)_alloc;
    }



   typedef int64_t _c_type;
  _c_type c;





  typedef boost::shared_ptr< ::learning_communication::AddnumsResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::learning_communication::AddnumsResponse_<ContainerAllocator> const> ConstPtr;

}; // struct AddnumsResponse_

typedef ::learning_communication::AddnumsResponse_<std::allocator<void> > AddnumsResponse;

typedef boost::shared_ptr< ::learning_communication::AddnumsResponse > AddnumsResponsePtr;
typedef boost::shared_ptr< ::learning_communication::AddnumsResponse const> AddnumsResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::learning_communication::AddnumsResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::learning_communication::AddnumsResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::learning_communication::AddnumsResponse_<ContainerAllocator1> & lhs, const ::learning_communication::AddnumsResponse_<ContainerAllocator2> & rhs)
{
  return lhs.c == rhs.c;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::learning_communication::AddnumsResponse_<ContainerAllocator1> & lhs, const ::learning_communication::AddnumsResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace learning_communication

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::learning_communication::AddnumsResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::learning_communication::AddnumsResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::learning_communication::AddnumsResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::learning_communication::AddnumsResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::learning_communication::AddnumsResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::learning_communication::AddnumsResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::learning_communication::AddnumsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "90f689545dad66929d15414b42274955";
  }

  static const char* value(const ::learning_communication::AddnumsResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x90f689545dad6692ULL;
  static const uint64_t static_value2 = 0x9d15414b42274955ULL;
};

template<class ContainerAllocator>
struct DataType< ::learning_communication::AddnumsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "learning_communication/AddnumsResponse";
  }

  static const char* value(const ::learning_communication::AddnumsResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::learning_communication::AddnumsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 c\n"
;
  }

  static const char* value(const ::learning_communication::AddnumsResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::learning_communication::AddnumsResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.c);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct AddnumsResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::learning_communication::AddnumsResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::learning_communication::AddnumsResponse_<ContainerAllocator>& v)
  {
    s << indent << "c: ";
    Printer<int64_t>::stream(s, indent + "  ", v.c);
  }
};

} // namespace message_operations
} // namespace ros

#endif // LEARNING_COMMUNICATION_MESSAGE_ADDNUMSRESPONSE_H
