dronecase: # *namespace*
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  

  # Position Controllers ---------------------------------------
  left_position_controller:
    type: effort_controllers/JointPositionController
    joint: top_cuboid_yp_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
  right_position_controller:
    type: effort_controllers/JointPositionController
    joint: top_cuboid_yn_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}